FROM python:3.12-slim AS runtime

WORKDIR /app

COPY . /src
RUN pip install --no-cache-dir /src /src/durabletask-azuremanaged azure-identity

COPY examples/serverless/remote_worker.py /app/remote_worker.py

EXPOSE 8080
ENTRYPOINT ["python", "/app/remote_worker.py"]
