# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from durabletask.azuremanaged.internal import serverless_activities_service_pb2 as durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in durabletask/azuremanaged/internal/serverless_activities_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServerlessActivitiesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectServerlessActivityWorker = channel.stream_unary(
                '/microsoft.durabletask.serverless.ServerlessActivities/ConnectServerlessActivityWorker',
                request_serializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.ServerlessActivityWorkerMessage.SerializeToString,
                response_deserializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.ServerlessActivityWorkerSessionResult.FromString,
                _registered_method=True)
        self.DeclareServerlessActivities = channel.unary_unary(
                '/microsoft.durabletask.serverless.ServerlessActivities/DeclareServerlessActivities',
                request_serializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.ServerlessActivityDeclaration.SerializeToString,
                response_deserializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.ServerlessActivityDeclarationResult.FromString,
                _registered_method=True)
        self.RemoveServerlessActivityDeclaration = channel.unary_unary(
                '/microsoft.durabletask.serverless.ServerlessActivities/RemoveServerlessActivityDeclaration',
                request_serializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.RemoveServerlessActivityDeclarationRequest.SerializeToString,
                response_deserializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.RemoveServerlessActivityDeclarationResult.FromString,
                _registered_method=True)


class ServerlessActivitiesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConnectServerlessActivityWorker(self, request_iterator, context):
        """Opens a live serverless activity worker session. The first message must be a
        start message with static worker metadata. Heartbeats carry dynamic state
        only. Closing the stream deregisters the worker.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeclareServerlessActivities(self, request, context):
        """Declares serverless activities before any live worker stream exists. This is a
        configuration contract and does not advertise active worker capacity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveServerlessActivityDeclaration(self, request, context):
        """Removes a serverless activity declaration so the backend stops waking new workers
        for the specified worker profile. Existing workers are not terminated by this RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerlessActivitiesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectServerlessActivityWorker': grpc.stream_unary_rpc_method_handler(
                    servicer.ConnectServerlessActivityWorker,
                    request_deserializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.ServerlessActivityWorkerMessage.FromString,
                    response_serializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.ServerlessActivityWorkerSessionResult.SerializeToString,
            ),
            'DeclareServerlessActivities': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclareServerlessActivities,
                    request_deserializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.ServerlessActivityDeclaration.FromString,
                    response_serializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.ServerlessActivityDeclarationResult.SerializeToString,
            ),
            'RemoveServerlessActivityDeclaration': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveServerlessActivityDeclaration,
                    request_deserializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.RemoveServerlessActivityDeclarationRequest.FromString,
                    response_serializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.RemoveServerlessActivityDeclarationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microsoft.durabletask.serverless.ServerlessActivities', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('microsoft.durabletask.serverless.ServerlessActivities', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServerlessActivities(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConnectServerlessActivityWorker(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/microsoft.durabletask.serverless.ServerlessActivities/ConnectServerlessActivityWorker',
            durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.ServerlessActivityWorkerMessage.SerializeToString,
            durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.ServerlessActivityWorkerSessionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeclareServerlessActivities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microsoft.durabletask.serverless.ServerlessActivities/DeclareServerlessActivities',
            durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.ServerlessActivityDeclaration.SerializeToString,
            durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.ServerlessActivityDeclarationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveServerlessActivityDeclaration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microsoft.durabletask.serverless.ServerlessActivities/RemoveServerlessActivityDeclaration',
            durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.RemoveServerlessActivityDeclarationRequest.SerializeToString,
            durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.RemoveServerlessActivityDeclarationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
