# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from durabletask.azuremanaged.internal import serverless_activities_service_pb2 as durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in durabletask/azuremanaged/internal/serverless_activities_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class OnDemandSandboxActivitiesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectOnDemandSandboxActivityWorker = channel.stream_unary(
                '/microsoft.durabletask.ondemandsandbox.OnDemandSandboxActivities/ConnectOnDemandSandboxActivityWorker',
                request_serializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.OnDemandSandboxActivityWorkerMessage.SerializeToString,
                response_deserializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.OnDemandSandboxActivityWorkerSessionResult.FromString,
                _registered_method=True)
        self.DeclareOnDemandSandboxActivities = channel.unary_unary(
                '/microsoft.durabletask.ondemandsandbox.OnDemandSandboxActivities/DeclareOnDemandSandboxActivities',
                request_serializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.OnDemandSandboxActivityDeclaration.SerializeToString,
                response_deserializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.OnDemandSandboxActivityDeclarationResult.FromString,
                _registered_method=True)
        self.RemoveOnDemandSandboxActivityDeclaration = channel.unary_unary(
                '/microsoft.durabletask.ondemandsandbox.OnDemandSandboxActivities/RemoveOnDemandSandboxActivityDeclaration',
                request_serializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.RemoveOnDemandSandboxActivityDeclarationRequest.SerializeToString,
                response_deserializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.RemoveOnDemandSandboxActivityDeclarationResult.FromString,
                _registered_method=True)


class OnDemandSandboxActivitiesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConnectOnDemandSandboxActivityWorker(self, request_iterator, context):
        """Opens a live on-demand sandbox activity worker session. The first message
        must be a start message with static worker metadata. Heartbeats carry
        dynamic state only. Closing the stream deregisters the worker.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeclareOnDemandSandboxActivities(self, request, context):
        """Declares on-demand sandbox activities before any live worker stream exists.
        This is a configuration contract and does not advertise active worker
        capacity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveOnDemandSandboxActivityDeclaration(self, request, context):
        """Removes an on-demand sandbox activity declaration so the backend stops
        waking new sandbox workers for the specified worker profile. Existing
        workers are not terminated by this RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OnDemandSandboxActivitiesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectOnDemandSandboxActivityWorker': grpc.stream_unary_rpc_method_handler(
                    servicer.ConnectOnDemandSandboxActivityWorker,
                    request_deserializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.OnDemandSandboxActivityWorkerMessage.FromString,
                    response_serializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.OnDemandSandboxActivityWorkerSessionResult.SerializeToString,
            ),
            'DeclareOnDemandSandboxActivities': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclareOnDemandSandboxActivities,
                    request_deserializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.OnDemandSandboxActivityDeclaration.FromString,
                    response_serializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.OnDemandSandboxActivityDeclarationResult.SerializeToString,
            ),
            'RemoveOnDemandSandboxActivityDeclaration': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveOnDemandSandboxActivityDeclaration,
                    request_deserializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.RemoveOnDemandSandboxActivityDeclarationRequest.FromString,
                    response_serializer=durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.RemoveOnDemandSandboxActivityDeclarationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microsoft.durabletask.ondemandsandbox.OnDemandSandboxActivities', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('microsoft.durabletask.ondemandsandbox.OnDemandSandboxActivities', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OnDemandSandboxActivities(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConnectOnDemandSandboxActivityWorker(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/microsoft.durabletask.ondemandsandbox.OnDemandSandboxActivities/ConnectOnDemandSandboxActivityWorker',
            durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.OnDemandSandboxActivityWorkerMessage.SerializeToString,
            durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.OnDemandSandboxActivityWorkerSessionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeclareOnDemandSandboxActivities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microsoft.durabletask.ondemandsandbox.OnDemandSandboxActivities/DeclareOnDemandSandboxActivities',
            durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.OnDemandSandboxActivityDeclaration.SerializeToString,
            durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.OnDemandSandboxActivityDeclarationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveOnDemandSandboxActivityDeclaration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microsoft.durabletask.ondemandsandbox.OnDemandSandboxActivities/RemoveOnDemandSandboxActivityDeclaration',
            durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.RemoveOnDemandSandboxActivityDeclarationRequest.SerializeToString,
            durabletask_dot_azuremanaged_dot_internal_dot_serverless__activities__service__pb2.RemoveOnDemandSandboxActivityDeclarationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
