name: Durable Task SDK (durabletask)

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"  # Only run for tags starting with "v"
  pull_request:
    branches: 
      - "main"

permissions:
  contents: read

jobs:
  lint-and-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
    - name: Set up Python 3.14
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: 3.14
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nox
    - name: Run lint checks
      run: nox -s lint

  run-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    needs: lint-and-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Node.js (needed for Azurite)
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22.x'

      - name: Cache npm
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-azurite

      - name: Install Azurite
        run: npm install -g azurite@latest

      - name: Install Nox
        run: |
          python -m pip install --upgrade pip
          pip install nox

      - name: Pytest unit tests
        run: nox -s core_tests-${{ matrix.python-version }}
